
FROM positron96/mxe_opencv

WORKDIR /build

# Build cross environment
RUN cd mxe && make --jobs $(nproc) qtbase

# Add a qmake alias
RUN ln -s /build/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 /build/mxe/usr/bin/qmake

##########################################################################

WORKDIR /src
