#!/bin/sh

#exec 1>&2

DIR=$(dirname "$0")

VER_FILE=${1:-"version.h"}

. $DIR/ver_incl.sh

echo "#pragma once" > $VER_FILE
echo "#define GIT_DATE \"$DATE\"" >> $VER_FILE
echo "#define GIT_HASH \"$HASH\"" >> $VER_FILE
echo "#define GIT_TAG \"$TAG\"">> $VER_FILE
echo "#define BUILD_DATE \"`date -Iseconds --utc`\"" >> $VER_FILE

