name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to GitHub Docker Registry
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: positron96
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        export TAG=docker.pkg.github.com/positron96/dockerfiles/mcu-eclipse-arm:$(date +%s)
        docker build mcu-eclipse-arm --tag $TAG
        docker push $TAG
         
      
