name: Docker Image CI

on: [push]

jobs:
  modified-folders:    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: create file list
        run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > files.txt
      - name: extract folders
        shell: python
        run: |
          import os
          files = open('files.txt', 'r').readlines()
          folders = [ s.strip().split('/')[0] for s in files if '/' in s]
          print('filter type:',folders)
          folders = list(set(folders))
          print('unique:',folders)
          folders = [ s for s in folders if os.path.isfile(s+'/Dockerfile')]
          print('filter by dockerfile exists:',folders); folders.extend(['preved', 'mcu-eclipse-arm']);
          open('folders.txt', 'w').write('\n'.join(folders))
          if len(folders)==0:
            print('Nothing to build')
            import sys
            sys.exit(1)
          
      - name: upload folder list
        uses: actions/upload-artifact@v1
        with:
          name: folder-list
          path: folders.txt


  build:

    runs-on: ubuntu-latest
    needs: modified-folders
    env:
      SHA8: ${GITHUB_SHA::8}

    steps:
    - uses: actions/checkout@v1
    - name: get folder list
      uses: actions/download-artifact@v1
      with:
        name: folder-list

    - name: Login to GitHub Docker Registry
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the images
      run: |
        ls folder-list
        cat folder-list/folders.txt
        while read f; do 
          echo $f
          export TAG=docker.pkg.github.com/${{ github.repository }}/$f:$(date --iso-8601)-$SHA8
          echo $TAG
          #docker build $f/ --tag $TAG
          #docker push $TAG          
        done < folder-list/folders.txt
        
         
      
